### PR TITLE
Manually fix upper bounds

### PR DESCRIPTION
**Pull request by clrcrl**
audit-helper: https://github.com/fishtown-analytics/dbt-audit-helper/blob/0.2.0/packages.yml

codegen: https://github.com/fishtown-analytics/dbt-codegen/blob/0.2.0/packages.yml

### CODE REVIEW

**Comment by drewbanin** [comment]
This LGTM, but it would be great if you could test out the fix by modifying the hub url in a `dbt deps` invocation!

**Comment by clrcrl** [comment]
Hmm, this didn't work:
```
 $ echo $DEFAULT_REGISTRY_BASE_URL
https://deploy-preview-259--flamboyant-mcclintock-92ba2d.netlify.app/

$ cat packages.yml
packages:
  - package: fishtown-analytics/audit_helper
    version: 0.2.0


$ dbt deps
Running with dbt=0.18.0-b2
Installing fishtown-analytics/audit_helper@0.2.0
  Installed from version 0.2.0

Installing fishtown-analytics/dbt_utils@0.4.1
  Installed from version 0.4.1

$ cat packages.yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.5.1
  - package: fishtown-analytics/audit_helper
    version: 0.2.0

$ dbt deps
Running with dbt=0.18.0-b2
Encountered an error:
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.5.1', '>=0.1.24', '<0.5.0']
```

**Comment by drewbanin** [comment]
i think the env var you want is `DBT_PACKAGE_HUB_URL` :)

**Comment by clrcrl** [comment]
oh right, I followed the instructions from yesterday, and forgot they were wrong! ha!

**Comment by clrcrl** [comment]
Works now!

**Pull request merged**
